### ISSUE TITLE
Unable to use the search bar since characters are replaced

### ISSUE THREAD

**Issue by okpierre** [seanvelasco/usky.app#74]
Here are a couple of example searches and the result

search for `olympics` -> final url `https://usky.app/search?q=cs`
search for `mastodon` -> final url `https://usky.app/search?q=n`

It seems to replace characters. On mobile it changes the letter uppercase/lowercase

The search was working before

edit: included video below

[usky-search.webm](https://github.com/user-attachments/assets/303c6243-c447-473c-ac9d-de34b47f2079)

**Comment by seanvelasco** [comment]
hi, pushed a fix for this! just let me know if you're still encountering the same problem.

as a side note, i'm pleasantly surprised to see the first issue raised on this repo. i wasn't aware that people were using this app, as I haven't shared it publicly. will make it a full-fledged app then!

thanks so much!!! pls let me know if you have other issues

**Comment by okpierre** [comment]
> hi, pushed a fix for this! just let me know if you're still encountering the same problem.
> 
> as a side note, i'm pleasantly surprised to see the first issue raised on this repo. i wasn't aware that people were using this app, as I haven't shared it publicly. will make it a full-fledged app then!
> 
> thanks so much!!! pls let me know if you have other issues

You're welcome! Glad to find a bug ;)

The search works much better now
